site_name: Característica de iKono Chat
site_url: https://iKonoChat.github.io
site_author: Alejandro Herrera
site_description: a short description of your website

nav:
  - Característica: index.md

theme:
  favicon: assets/images/favicon.png
  name: material
  logo: assets/logo.png
  features:
    - toc.integrate
  language: es
  palette:
    - media: "(prefers-color-scheme: light)"

      scheme: ikono
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"

      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
extra_css:
  - stylesheets/extra.css


